Repository neutrinoceros/yt_idefix, pull requests merged in 2022-02, with the labels that each got.

#80 RFC: disantangle metadata parsing for vtk files, centralize geometry validation
  setup.cfg
  tests/test_vtk.py
  yt_idefix/__init__.py
  yt_idefix/_io/commons.py
  yt_idefix/_io/dmp_io.py
  yt_idefix/_io/vtk_io.py
  yt_idefix/data_structures.py
  yt_idefix/loaders.py
Labels: enhancement

#87 MNT: reallow compat with yt 4.0.1
  setup.cfg
  yt_idefix/__init__.py
  yt_idefix/loaders.py
Labels: bug

#92 BUG: fix loading PlutoVtkDataset from parent dir
  tests/test_loading.py
  yt_idefix/data_structures.py
Labels: bug, code: Pluto

#90 BUG: fix incorrect conversion between code_time and cgs_unit
  tests/conftest.py
  tests/data/FargoMHDSpherical/meta.yaml
  tests/data/cataclysmic-disk/meta.yaml
  tests/data/khi/meta.yaml
  tests/data/pluto_disk_planet/meta.yaml
  tests/data/pluto_rotor/meta.yaml
  tests/data/pluto_sedov/meta.yaml
  tests/data/pluto_sod/meta.yaml
  tests/test_vtk.py
  yt_idefix/data_structures.py
Labels: bug, code: Pluto
