Repository neutrinoceros/yt_idefix, pull requests merged in 2023-03, with the labels that each got.

#225 TST: add test infra for XDMF data
  tests/conftest.py
Labels: code: Pluto, io: hdf5

#226 TST: fix test unique ids when using multiple paths with '.h5' extension
  tests/conftest.py
Labels: bug, tests

#230 RFC: move _set_code_unit_attributes from PlutoVtkDataset to StaticPlutoDataset
  yt_idefix/data_structures.py
Labels: code: Pluto

#231 RFC: more more of PlutoVtkDataset's logic to super class
  yt_idefix/data_structures.py
Labels: code: Pluto

#234 TST: adapt conftest.py so that pluto vtk files with no units don't fail tests
  tests/test_vtk.py
Labels: code: Pluto, tests

#209 PLUTO xdmf dump support
  .github/workflows/ci.yml
  .gitignore
  pyproject.toml
  tests/test_xdmf.py
  yt_idefix/_io/commons.py
  yt_idefix/_io/h5_io.py
  yt_idefix/_io/vtk_io.py
  yt_idefix/api.py
  yt_idefix/data_structures.py
  yt_idefix/fields.py
  yt_idefix/io.py
Labels: code: Pluto, io: hdf5

#242 DOC: assemble support information in a table
  README.md
Labels: documentation
